### PR TITLE
Struggling with colons in server on-the-fly-build

### LINKED ISSUE #536: Struggling with colons in server on-the-fly-build
Steps to reproduce; visit `http://localhost:3000/en-us/docs/web/css/::-webkit-scrollbar`

In the `server` you get:

```
11:06:06 AM server.1      |  Successfully on-the-fly built undefined (7ms)
11:06:06 AM server.1      |  TypeError: path argument is required to res.sendFile
11:06:06 AM server.1      |      at ServerResponse.sendFile (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/response.js:411:11)
11:06:06 AM server.1      |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/server/index.js:187:15
11:06:06 AM server.1      |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
11:06:06 AM server.1      |      at next (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:137:13)
11:06:06 AM server.1      |      at Route.dispatch (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/route.js:112:3)
11:06:06 AM server.1      |      at Layer.handle [as handle_request] (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/layer.js:95:5)
11:06:06 AM server.1      |      at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:281:22
11:06:06 AM server.1      |      at param (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:354:14)
11:06:06 AM server.1      |      at param (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:365:14)
11:06:06 AM server.1      |      at Function.process_params (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/node_modules/express/lib/router/index.js:410:3)
```

NOTE The invalid `Successfully on-the-fly built undefined`  first line.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #536

Steps to test:

1. `yarn clean && yarn start`
2. Go to the home page: http://localhost:3000
3. Search for `::-webkit-scrollbar` and click on the matching search result
4. Works? 
5. Refresh the page.
6. Works?

### CODE REVIEW

**Comment by peterbe** [comment]
That [second commit](https://github.com/mdn/stumptown-renderer/pull/544/commits/96b25664c8dd7de9657c93f0c80ba8aa5605f163) was "necessary" because if you pretend that you're Travis and run `CI=true ./scripts/ci-end-to-end.sh` on you laptop you get the sample content.

**Comment by peterbe** [comment]
Almost an hour later, Travis still hasn't figured out that the [checks passed](https://travis-ci.org/github/mdn/stumptown-renderer/builds/683541359) :(

File: content/scripts/build.js [hunk 1]
```diff
@@ -1070,9 +1070,13 @@ class Builder {
       fs.existsSync(hashDestination) &&
       fs.readFileSync(hashDestination, "utf8") === combinedHash
     ) {
+      // XXX If you delete the 'index.html' and/or the 'index.json' file
+      // but leave the folder and the 'index.hash' file, this code here
+      // will wrongfully say the it's already built.
```
Comment (escattone) [inline content/scripts/build.js:1204]: Good catch! I think we should create an issue for that.
