### PR TITLE
'yarn deployment-build' isn't exiting early

### LINKED ISSUE #155: 'yarn deployment-build' isn't exiting early
Right now our stumptown-content git submodule pointer is a bit messed up. There's stuff built in `stumptown/packaged/` that's causing errors to be thrown but it still carries on. 

Steps to reproduce:

```
▶ yarn deployment-build
...
{
  type: 'link_list',
  value: { title: 'Learn HTML', content: [ [Object], [Object] ] }
}
Rendering HTML failed!
      uri=/en-US/docs/Web/HTML
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/HTML.json
(node:4734) UnhandledPromiseRejectionWarning: Error: No idea how to handle a 'link_list' section
    at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:191:13
    at Array.map (<anonymous>)
    at map (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:148:19)
    at processChild (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:1)
    at resolve (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:1)
    at ReactDOMServerRenderer.render (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:1)
    at ReactDOMServerRenderer.read (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:1)
    at renderToString (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:1)
    at ./render.js.__webpack_exports__.default (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/render.js:31:34)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:118:24)
(node:4734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4734) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{
  type: 'example',
  value: {
    description: {
      title: 'Specifying colors in stylesheets',
...
✨  Done in 19.57s.

▶ echo $?
0
```

In `stumptown/packaged/html/HTML.json` there's a key on the `document.body` that is currently unsupported. I.e. we don't have a React component to deal with it. That's a real problem but the pressing problem is that that error isn't dealt with properly. 

If the renderer's `cli` can't deal with the `stumptown-content` it should fail hard break things. It basically means that the `stumptown-renderer` and `stumptown-content` disagree and need to sync up. 
Somewhere we allowed the git submodule upgrade to happen because TravisCI probably didn't fail even though it should.

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #155

This one was tricky. Promises and async/await is fine until you actually need to really care and do something sane with the possible exceptions. Errors thrown deep inside `client/src/*.js` in some React component is totally something that's going to happen from time to time as we're making mistakes. What matters here is that we deal with it properly in the `cli`. What also matters here is that if *any* error happens, it should break the build. I.e. the `cli` should fail with a non-zero exit code. 

Here's the output of running this patch:

```
▶ CLI_BUILD_HTML=true yarn workspace cli start

<snipped to save space>

Rendering HTML failed!
      uri=/en-US/docs/Web/HTML
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/HTML.json
Error: No idea how to handle a 'link_list' section
    at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:191:13
    at Array.map (<anonymous>)
    at map (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:148:19)
    at processChild (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:1)
    at resolve (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:1)
    at ReactDOMServerRenderer.render (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:1)
    at ReactDOMServerRenderer.read (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:1)
    at renderToString (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:1)
    at ./render.js.__webpack_exports__.default (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/render.js:31:34)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:118:24)
Rendering HTML failed!
      uri=/en-US/docs/HTML/Elements
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/reference/elements.json
Error: No idea how to handle a 'link_list' section
    at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:191:13
    at Array.map (<anonymous>)
    at map (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:148:19)
    at processChild (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:1)
    at resolve (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:1)
    at ReactDOMServerRenderer.render (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:1)
    at ReactDOMServerRenderer.read (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:1)
    at renderToString (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:1)
    at ./render.js.__webpack_exports__.default (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/render.js:31:34)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:118:24)
Rendering HTML failed!
      uri=/en-US/docs/Web/HTML/Applying_color
      filePath=/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/stumptown/packaged/html/guides/Applying_color.json
Error: No idea how to handle a 'example' section
    at /Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:191:13
    at Array.map (<anonymous>)
    at map (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/.ent/src/document.js:148:19)
    at processChild (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3090:1)
    at resolve (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:1)
    at ReactDOMServerRenderer.render (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:1)
    at ReactDOMServerRenderer.read (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:1)
    at renderToString (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:1)
    at ./render.js.__webpack_exports__.default (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/render.js:31:34)
    at buildHtmlAndJson (/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli/dist/webpack:/index.js:118:24)
Wrote ../client/build/en-US/docs/Web/HTML/Element/address/index.json and ../client/build/en-US/docs/Web/HTML/Element/address/index.html 184ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/abbr/index.json and ../client/build/en-US/docs/Web/HTML/Element/abbr/index.html 91ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/aside/index.json and ../client/build/en-US/docs/Web/HTML/Element/aside/index.html 34ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/article/index.json and ../client/build/en-US/docs/Web/HTML/Element/article/index.html 39ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/b/index.json and ../client/build/en-US/docs/Web/HTML/Element/b/index.html 24ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/audio/index.json and ../client/build/en-US/docs/Web/HTML/Element/audio/index.html 99ms

<snipped to save space>

Wrote ../client/build/en-US/docs/Web/HTML/Element/li/index.json and ../client/build/en-US/docs/Web/HTML/Element/li/index.html 22ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/legend/index.json and ../client/build/en-US/docs/Web/HTML/Element/legend/index.html 18ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/video/index.json and ../client/build/en-US/docs/Web/HTML/Element/video/index.html 60ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/table/index.json and ../client/build/en-US/docs/Web/HTML/Element/table/index.html 60ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
```

What's happening is that I happen to know that there are 3 documents in stumptown/packaged/ that are currently incompatible with our stumptown-renderer React code. It's fine. We'll deal with it when time allows. 

But the critical thing is that all 3 stacktraces are printed with `console.error`. I think this'll help when you're reviewing the full logs on something like TravisCI. Naive use of `Promise.all(promises).then(values => { ... }).catch(err => { console.log('At least one failed!'); console.error(err) }` sucks because you only get to see 1 error.

And most critically, the final `run(paths).catch()` means that at a low level we get to know that 1 or more threw so we have to exit with non-zero.

### CODE REVIEW

**Comment by peterbe** [comment]
It was a mistake of us to allow this git submodule to upgrade and land in master. We shouldn't be using this version of `stumptown-content` (as a git submodule) yet because we don't have the necessary React components to deal with certain things that `stumptown-content` packaged. 
We'll deal with it in due course. The most important thing is that I think TravisCI should protect us from upgrading the git submodule pointer if renderer isn't compatible with the content.

**Comment by peterbe** [comment]
@Gregoor At the moment, I'm expecting this to fail Travis. ...which it correctly does. 
This is what we needed before we let the stumptown-content git submodule upgrade to the latest version. (my fault).

**Comment by peterbe** [comment]
If you approve, I'd be happy to merge this to master and redirect the attention to https://github.com/mdn/stumptown-renderer/issues/157

**Comment by peterbe** [comment]
>  I'll definitely accept blame here.

Feel free to accept about 1% blame. :)
Also, the word blame sucks because it carries a negative connotation which can put unnecessary pressure on individuals.

**Comment by peterbe** [comment]
@wbamberg I'm not asking for a code review but I'd like you to be aware of this work. The idea is that if we have 100 .json files to process, we start 100 async tasks. If any single one of them fails, the whole program fails but it will at least `console.error` every single traceback. In a sync world, you'd just crash and bail on the first possible error. 

Like with running the unit tests in Kuma, we configure our `pytest` very similarly. We have hundreds of individual tests. If a single one fails, TravisCI fails but you get a chance to see *all* the tracebacks. That's what this PR is all about; to match that behavior.

File: cli/index.js [hunk 1]
```diff
@@ -290,17 +290,17 @@ function run(paths) {
...
         .then(() => {
           return buildHtmlAndJson({
             filePath,
             output,
             buildHtml: args["build-html"],
             quiet: args["quiet"]
           });
+        })
+        .catch(ex => {
+          console.error(ex);
```
Comment (Gregoor) [inline cli/index.js]: why not log the error at the highest level (i.e. when catching run) and omit this skip call?

File: client/src/document.js [hunk 2]
```diff
@@ -183,11 +183,11 @@ function RenderDocumentBody({ doc }) {
     } else if (section.type === "info_box") {
       // XXX Unfinished!
       // https://github.com/mdn/stumptown-content/issues/106
-      console.warn("Don't know how to deal with info_box!");
+      // console.warn("Don't know how to deal with info_box!");
       // console.log(section);
       return null;
     } else {
-      console.warn(section);
+      // console.warn(section);
```
Comment (Gregoor) [inline client/src/document.js]: nit: dead code

File: cli/index.js (hunk 1 above)
Comment (peterbe) [reply cli/index.js]: I'm not sure I understand. This catches any error within `buildHtmlAndJson` in general. Now, *inside* `buildHtmlAndJson` it might do its own error handling of individual stuff.
